### ISSUE TITLE
Which OS on the Hikey970?

### ISSUE THREAD

**Issue by janrinze** [bharshal/ai-gan#1]
Hi the project description mentions a custom OS for the Hikey 970, is here info on that OS?

**Comment by bharshal** [comment]
Hi,
Yes there is a custom os for HiKey 970. It is an Embedded Linux Debian distro made by me and my team. You can find the latest stable release at
this link :

http://www.lemaker.org/product-hikey970-download-85.html

**Comment by janrinze** [comment]
Aha, is that the one with Tensorflow enabled? That's the one I am running. Wish it would be possible to have OpenGLES enabled for X11 and access to the NPU too.

**Comment by bharshal** [comment]
As I am no longer working with the team, I have no idea about the latest releases. Most probably it does have Tensorflow enabled in it. For NPU access though, it'll take quite some time as the libraries have to be released by the chip maker.

**Comment by rihun-kim** [comment]
Hi, I have two question about hikey970..

1) Did you port ubuntu 18.04 on hikey970 board successfully?

2) How can I see grub menu?
hikey board turn on -> black screen -> shunya login window...
I want to see grub menu....
